# -*- coding: ascii -*-
#  ______ _ _      _____            _       _____ _ _            _
# |  ____(_) |    |  __ \          | |     / ____| (_)          | |
# | |__   _| | ___| |__) |___   ___| | __ | |    | |_  ___ _ __ | |_
# |  __| | | |/ _ \  _  // _ \ / __| |/ / | |    | | |/ _ \ '_ \| __|
# | |    | | |  __/ | \ \ (_) | (__|   <  | |____| | |  __/ | | | |_
# |_|    |_|_|\___|_|  \_\___/ \___|_|\_\  \_____|_|_|\___|_| |_|\__|
#
# Copyright (C) 2012 Heyware s.r.l.
#
# This file is part of FileRock Client.
#
# FileRock Client is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FileRock Client is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FileRock Client. If not, see <http://www.gnu.org/licenses/>.
#

"""
This is the ListDialog module.




----

This module is part of the FileRock Client.

Copyright (C) 2012 - Heyware s.r.l.

FileRock Client is licensed under GPLv3 License.

"""

# generated by wxGlade 0.6.3 on Fri Jul 27 16:05:41 2012

import wx
import os
import logging

from filerockclient.ui.wxGui.constants import IMAGE_PATH

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ListDialog(wx.Dialog):
    def __init__(self, parent, app, msg, title, list, *args, **kwds):
        # begin wxGlade: ListDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, parent, *args, **kwds)
        pathname = os.path.join(IMAGE_PATH, "stop-64.png")
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap(pathname, wx.BITMAP_TYPE_PNG))
        self.message_label = wx.StaticText(self, -1, "Basis Mismatch")
        self.list_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.app = app
        self.logger = logging.getLogger("FR.Gui"+self.__class__.__name__)
        self.message_label.SetLabel(msg)
        font = self.message_label.GetFont()
        font.SetWeight(wx.FONTWEIGHT_BOLD)
        self.message_label.SetFont(font)

        self.sizer_2.Add(self.CreateStdDialogButtonSizer(wx.OK), 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 15)
        self.SetTitle(title)
        for item in list:
            self.list_ctrl.AppendText(item+'\n')
        self.Layout()

    def __set_properties(self):
        # begin wxGlade: ListDialog.__set_properties
        self.SetTitle("Sync Report")
        self.SetSize((700, 560))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ListDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 20)
        grid_sizer_2.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.message_label, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_2, 0, wx.ALL|wx.EXPAND, 15)
        sizer_3.Add(self.list_ctrl, 1, wx.ALL|wx.EXPAND, 10)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
        self.sizer_2 = sizer_2

# end of class ListDialog


