# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='shellext.proto',
  package='filerock.shellext',
  serialized_pb='\n\x0eshellext.proto\x12\x11\x66ilerock.shellext\"\xd1\x01\n\x07Request\x12.\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x1d.filerock.shellext.Request.Id\x12\x14\n\taction_id\x18\x02 \x01(\r:\x01\x30\x12\x10\n\x08pathname\x18\x03 \x03(\t\"n\n\x02Id\x12\x15\n\x11QUERY_PATH_STATUS\x10\x00\x12\x1b\n\x17QUERY_PATH_CONTEXT_MENU\x10\x01\x12\x1b\n\x17QUERY_FULL_CONTEXT_MENU\x10\x02\x12\x17\n\x13\x45XECUTE_MENU_ACTION\x10\x03\"\xc6\x01\n\x06Status\x12\x42\n\x06status\x18\x01 \x01(\x0e\x32$.filerock.shellext.Status.FileStatus:\x0cGOT_NO_REPLY\"x\n\nFileStatus\x12\x10\n\x0cGOT_NO_REPLY\x10\x00\x12\x10\n\x0cOK_CLEARTEXT\x10\x01\x12\x10\n\x0cOK_ENCRYPTED\x10\x02\x12\x10\n\x0cSYNCRONIZING\x10\x03\x12\x10\n\x0cINTEGRITY_KO\x10\x04\x12\x10\n\x0cSTILL_UNSEEN\x10\x05\"w\n\x04Menu\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.filerock.shellext.Menu.Item\x1a\x42\n\x04Item\x12\n\n\x02id\x18\x01 \x02(\r\x12\r\n\x05label\x18\x02 \x02(\t\x12\x11\n\thelp_text\x18\x03 \x02(\t\x12\x0c\n\x04verb\x18\x04 \x02(\t')



_REQUEST_ID = descriptor.EnumDescriptor(
  name='Id',
  full_name='filerock.shellext.Request.Id',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='QUERY_PATH_STATUS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUERY_PATH_CONTEXT_MENU', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUERY_FULL_CONTEXT_MENU', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXECUTE_MENU_ACTION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=137,
  serialized_end=247,
)

_STATUS_FILESTATUS = descriptor.EnumDescriptor(
  name='FileStatus',
  full_name='filerock.shellext.Status.FileStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GOT_NO_REPLY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OK_CLEARTEXT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OK_ENCRYPTED', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SYNCRONIZING', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTEGRITY_KO', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STILL_UNSEEN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=328,
  serialized_end=448,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='filerock.shellext.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='filerock.shellext.Request.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action_id', full_name='filerock.shellext.Request.action_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pathname', full_name='filerock.shellext.Request.pathname', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_ID,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=247,
)


_STATUS = descriptor.Descriptor(
  name='Status',
  full_name='filerock.shellext.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='filerock.shellext.Status.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUS_FILESTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=250,
  serialized_end=448,
)


_MENU_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='filerock.shellext.Menu.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='filerock.shellext.Menu.Item.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='filerock.shellext.Menu.Item.label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='help_text', full_name='filerock.shellext.Menu.Item.help_text', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='verb', full_name='filerock.shellext.Menu.Item.verb', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=503,
  serialized_end=569,
)

_MENU = descriptor.Descriptor(
  name='Menu',
  full_name='filerock.shellext.Menu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='filerock.shellext.Menu.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MENU_ITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=450,
  serialized_end=569,
)

_REQUEST.fields_by_name['command'].enum_type = _REQUEST_ID
_REQUEST_ID.containing_type = _REQUEST;
_STATUS.fields_by_name['status'].enum_type = _STATUS_FILESTATUS
_STATUS_FILESTATUS.containing_type = _STATUS;
_MENU_ITEM.containing_type = _MENU;
_MENU.fields_by_name['items'].message_type = _MENU_ITEM
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Menu'] = _MENU

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:filerock.shellext.Request)

class Status(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUS
  
  # @@protoc_insertion_point(class_scope:filerock.shellext.Status)

class Menu(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Item(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MENU_ITEM
    
    # @@protoc_insertion_point(class_scope:filerock.shellext.Menu.Item)
  DESCRIPTOR = _MENU
  
  # @@protoc_insertion_point(class_scope:filerock.shellext.Menu)

# @@protoc_insertion_point(module_scope)
