# -*- coding: ascii -*-
#  ______ _ _      _____            _       _____ _ _            _
# |  ____(_) |    |  __ \          | |     / ____| (_)          | |
# | |__   _| | ___| |__) |___   ___| | __ | |    | |_  ___ _ __ | |_
# |  __| | | |/ _ \  _  // _ \ / __| |/ / | |    | | |/ _ \ '_ \| __|
# | |    | | |  __/ | \ \ (_) | (__|   <  | |____| | |  __/ | | | |_
# |_|    |_|_|\___|_|  \_\___/ \___|_|\_\  \_____|_|_|\___|_| |_|\__|
#
# Copyright (C) 2012 Heyware s.r.l.
#
# This file is part of FileRock Client.
#
# FileRock Client is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FileRock Client is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FileRock Client. If not, see <http://www.gnu.org/licenses/>.
#

"""
This is the MainWindow module.




----

This module is part of the FileRock Client.

Copyright (C) 2012 - Heyware s.r.l.

FileRock Client is licensed under GPLv3 License.

"""
# generated by wxGlade 0.6.3 on Tue Jun 26 22:31:17 2012

import wx
import os

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from filerockclient.ui.wxGui.Utils import MywxStaticText
# end wxGlade


class MainWindow(wx.Frame):
    def __init__(self, images_dir, icons_dir, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.SYSTEM_MENU|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.images_dir = images_dir
        self.icons_dir = icons_dir
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Used Space")
        self.folder_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("other/folder-48.png"), wx.BITMAP_TYPE_ANY))
        self.folder_label = wx.StaticText(self, -1, "Open Folder")
        self.status_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("GUI-icons/dialog-information-48.png"), wx.BITMAP_TYPE_ANY))
        self.status_label = wx.StaticText(self, -1, "Status")
        self.activity_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("GUI-icons/activity-48.png"), wx.BITMAP_TYPE_ANY))
        self.activity_label = wx.StaticText(self, -1, "Activity")
        self.preferences_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("GUI-icons/preferences-system-48.png"), wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.preferences_label = wx.StaticText(self, -1, "Options")
        self.start_stop_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("GUI-icons/pause-48-tango.png"), wx.BITMAP_TYPE_ANY))
        self.start_stop_label = wx.StaticText(self, -1, "Pause")
        self.logs_bitmap_button = wx.BitmapButton(self, -1, wx.Bitmap(self._image_path("GUI-icons/logs-48.png"), wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.logs_label = wx.StaticText(self, -1, "Logs")
        self.space_ctrl = MywxStaticText(self, -1, "--- Mb of -- Gb")
        self.used_space_bar = wx.Gauge(self, -1, 1000)
        self.get_more_space_button = wx.Button(self, -1, "Get More Space", style=wx.BU_EXACTFIT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnFileRockFolder, self.folder_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnStatusClick, self.status_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnActivityClick, self.activity_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnPreferencesClick, self.preferences_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnStartStop, self.start_stop_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnLogsClick, self.logs_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.OnGetMoreSpace, self.get_more_space_button)
        # end wxGlade

        self.buttons = {
                        'status': self.status_bitmap_button,
                        'activity': self.activity_bitmap_button,
                        'preferences': self.preferences_bitmap_button
                        }

    def _image_path(self, name):
        return os.path.join(self.images_dir, name)

    def _icon_path(self, name):
        return os.path.join(self.icons_dir, name)

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle("FileRock")
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.folder_bitmap_button.SetSize(self.folder_bitmap_button.GetBestSize())
        self.status_bitmap_button.SetSize(self.status_bitmap_button.GetBestSize())
        self.activity_bitmap_button.SetSize(self.activity_bitmap_button.GetBestSize())
        self.preferences_bitmap_button.SetSize(self.preferences_bitmap_button.GetBestSize())
        self.start_stop_bitmap_button.SetSize(self.start_stop_bitmap_button.GetBestSize())
        self.logs_bitmap_button.SetSize(self.logs_bitmap_button.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_3_copy = wx.FlexGridSizer(1, 3, 0, 7)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.GridSizer(1, 6, 0, 10)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_12.Add(self.folder_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_12.Add(self.folder_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grid_sizer_4.Add(sizer_12, 0, wx.EXPAND, 5)
        sizer_6.Add(self.status_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_6.Add(self.status_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grid_sizer_4.Add(sizer_6, 0, wx.EXPAND, 5)
        sizer_7.Add(self.activity_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.activity_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_4.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_9.Add(self.preferences_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_9.Add(self.preferences_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_4.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_11.Add(self.start_stop_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_11.Add(self.start_stop_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grid_sizer_4.Add(sizer_11, 0, wx.EXPAND, 5)
        sizer_10.Add(self.logs_bitmap_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_10.Add(self.logs_label, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_4.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_4, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.ALIGN_CENTER_HORIZONTAL, 15)
        sizer_1.Add(sizer_2, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 10)
        sizer_3_copy.Add(self.space_ctrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.used_space_bar, 1, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_3_copy.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3_copy.Add(self.get_more_space_button, 0, 0, 5)
        sizer_3_copy.AddGrowableCol(1)
        sizer_3.Add(sizer_3_copy, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizer_1.Add(sizer_3, 0, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade
        self.sizer_2 = sizer_2

    def OnStatusClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnStatusClick' not implemented"
        event.Skip()

    def OnActivityClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnActivityClick' not implemented"
        event.Skip()

    def OnPreferencesClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnPreferencesClick' not implemented"
        event.Skip()

    def OnLogsClick(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnLogsClick' not implemented"
        event.Skip()

    def OnGetMoreSpace(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnGetMoreSpace' not implemented"
        event.Skip()

    def OnStartStop(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnStartStop' not implemented"
        event.Skip()

    def OnFileRockFolder(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `OnFileRockFolder' not implemented"
        event.Skip()

# end of class MainWindow


